name: Build & test

on: [push]

jobs:
  lint_build_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: yarn
      env:
        CI: true
    - name: lint
      run: yarn lint
      env:
        CI: true
    - name: build & test
      run: yarn build && yarn test:unit
      env:
        CI: true
